<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_585a52994daa4',
    'title' => 'Dishes',
    'fields' => array (
        array (
            'key' => 'field_585a52a225278',
            'label' => 'Dish name',
            'name' => 'dish_name',
            'type' => 'text',
            'instructions' => 'Enter the name of the dish/drink.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_585a54408ade4',
            'label' => 'Dish description',
            'name' => 'dish_description',
            'type' => 'textarea',
            'instructions' => 'Describe the dish.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
        ),
        array (
            'key' => 'field_586f979b662b3',
            'label' => 'Dish price',
            'name' => 'dish_price',
            'type' => 'number',
            'instructions' => 'The price of the dish.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '$',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'dishes',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'custom_fields',
        4 => 'discussion',
        5 => 'comments',
        6 => 'revisions',
        7 => 'slug',
        8 => 'author',
        9 => 'format',
        10 => 'featured_image',
        11 => 'categories',
        12 => 'tags',
        13 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_586e9326d5b75',
    'title' => 'Extra content',
    'fields' => array (
        array (
            'key' => 'field_586e932deed4a',
            'label' => 'Extra content',
            'name' => 'extra_content',
            'type' => 'wysiwyg',
            'instructions' => 'Text for the second column.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'templates/two-column.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58629311542d0',
    'title' => 'Flexible',
    'fields' => array (
        array (
            'key' => 'field_5862931f82835',
            'label' => 'Content',
            'name' => 'content',
            'type' => 'flexible_content',
            'instructions' => 'Add sections to the page',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add Row',
            'min' => '',
            'max' => '',
            'layouts' => array (
                array (
                    'key' => '586e4169e642d',
                    'name' => 'blurb',
                    'label' => 'Blurb',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_586e4178e642e',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Title for the blurb',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_586e4186e642f',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'instructions' => 'Text for the blurb.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'wpautop',
                        ),
                        array (
                            'key' => 'field_586e41ade6431',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'page_link',
                            'instructions' => 'Link to page.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array (
                            ),
                            'taxonomy' => array (
                            ),
                            'allow_null' => 0,
                            'allow_archives' => 1,
                            'multiple' => 0,
                        ),
                        array (
                            'key' => 'field_586e41bae6432',
                            'label' => 'Button text',
                            'name' => 'button_text',
                            'type' => 'text',
                            'instructions' => 'Button text.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5862932b37a60',
                    'name' => 'recent_news',
                    'label' => 'Recent News',
                    'display' => 'block',
                    'sub_fields' => array (
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '58667c4007c7e',
                    'name' => 'slider',
                    'label' => 'Slider',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_58667c8507c80',
                            'label' => 'Add image',
                            'name' => 'add_image',
                            'type' => 'repeater',
                            'instructions' => 'Add images for slideshow.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => '',
                            'max' => '',
                            'layout' => 'table',
                            'button_label' => 'Add image',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_58667ca707c81',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '586a86150c3ef',
                    'name' => 'break_line',
                    'label' => 'Break line',
                    'display' => 'block',
                    'sub_fields' => array (
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '58679c2ee06a7',
                    'name' => 'image_gallery',
                    'label' => 'Image gallery',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_586a97dd4a7a4',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Gallery titel.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_58679ca1e06a8',
                            'label' => 'gallery',
                            'name' => 'gallery',
                            'type' => 'gallery',
                            'instructions' => 'Images to show in gallery.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => '',
                            'max' => '',
                            'insert' => 'append',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_5870f57f805e5',
                            'label' => 'Pictures per row',
                            'name' => 'img_row',
                            'type' => 'select',
                            'instructions' => 'How many pictures per row?',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                6 => '2',
                                4 => '3',
                                3 => '4',
                            ),
                            'default_value' => array (
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            ),
            array (
                'param' => 'page',
                'operator' => '!=',
                'value' => '242',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_585bf18591955',
    'title' => 'Global',
    'fields' => array (
        array (
            'key' => 'field_586e3c0ac8744',
            'label' => 'Header',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_585bf219fb2aa',
            'label' => 'Social media header',
            'name' => 'socialmedia_header',
            'type' => 'repeater',
            'instructions' => 'Add your social media to show in header.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Lägg till rad',
            'sub_fields' => array (
                array (
                    'key' => 'field_585bf243fb2ac',
                    'label' => 'Icon',
                    'name' => 'icon',
                    'type' => 'select',
                    'instructions' => 'Choose your icon here.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'facebook' => 'Facebook',
                        'instagram' => 'Instagram',
                        'twitter' => 'Twitter',
                        'youtube' => 'Youtube',
                    ),
                    'default_value' => array (
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array (
                    'key' => 'field_585bf22efb2ab',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'url',
                    'instructions' => 'Type your link here.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        array (
            'key' => 'field_5873a744d8b54',
            'label' => 'Opening Hours',
            'name' => 'opening_hours_header',
            'type' => 'true_false',
            'instructions' => 'Display todays opening hours in header?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
        ),
        array (
            'key' => 'field_585bfaa55c309',
            'label' => 'Footer',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_586e3500c052a',
            'label' => 'Text adress',
            'name' => 'text_adress',
            'type' => 'textarea',
            'instructions' => 'Type your adress here.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586e352cc052b',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
        ),
        array (
            'key' => 'field_586e352cc052b',
            'label' => 'Map choice',
            'name' => 'map_choice',
            'type' => 'true_false',
            'instructions' => 'Do you want a map instead of text?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Yes',
            'default_value' => 0,
        ),
        array (
            'key' => 'field_586e3464c0529',
            'label' => 'I-frame code',
            'name' => 'iframe_code',
            'type' => 'text',
            'instructions' => 'Paste your google maps iframe code here. Choose the small format.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586e352cc052b',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_58628f29df522',
            'label' => 'Phone number',
            'name' => 'phone_number',
            'type' => 'text',
            'instructions' => 'Type your phone number here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_586e4ea652c00',
            'label' => 'Phone number header',
            'name' => 'phone_number_header',
            'type' => 'true_false',
            'instructions' => 'Show phone number in header?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Ok!',
            'default_value' => 0,
        ),
        array (
            'key' => 'field_586fab24ba4d2',
            'label' => 'Email',
            'name' => 'email',
            'type' => 'email',
            'instructions' => 'Type your email-adress here.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586e352cc052b',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_585bf36a80557',
            'label' => 'Opening hours',
            'name' => 'opening_hours',
            'type' => 'wysiwyg',
            'instructions' => 'Type the opening hours here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
            'key' => 'field_586e3c1c306a9',
            'label' => 'Social media footer',
            'name' => 'socialmedia_footer',
            'type' => 'repeater',
            'instructions' => 'Add your social media to footer.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Lägg till rad',
            'sub_fields' => array (
                array (
                    'key' => 'field_586e3c1c306ab',
                    'label' => 'Icon',
                    'name' => 'icon',
                    'type' => 'select',
                    'instructions' => 'Choose your icon here.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'facebook' => 'Facebook',
                        'instagram' => 'Instagram',
                        'twitter' => 'Twitter',
                        'youtube' => 'Youtube',
                    ),
                    'default_value' => array (
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array (
                    'key' => 'field_586e3c1c306aa',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'url',
                    'instructions' => 'Type the link here.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        array (
            'key' => 'field_5874b0565682e',
            'label' => 'Contact form',
            'name' => 'contact_form',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
            'key' => 'field_5874b0945682f',
            'label' => 'Copyright Name',
            'name' => 'copy_name',
            'type' => 'text',
            'instructions' => 'Copyright name here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5874b09656830',
            'label' => 'Starting year',
            'name' => 'starting_year',
            'type' => 'number',
            'instructions' => 'The starting year for copyright.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array (
            'key' => 'field_585c19c0d5910',
            'label' => 'Background images',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_585c1ec964a4c',
            'label' => 'Frontpage',
            'name' => 'background_frontpage',
            'type' => 'image',
            'instructions' => 'Background image for front page.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_585c230d2f117',
            'label' => 'Menu',
            'name' => 'background_menu',
            'type' => 'image',
            'instructions' => 'Background image for food menu.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_585c20cada442',
            'label' => 'News',
            'name' => 'background_news',
            'type' => 'image',
            'instructions' => 'Background image for news page.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_585c20c2da441',
            'label' => 'About us',
            'name' => 'background_about',
            'type' => 'image',
            'instructions' => 'Background image for the about us page.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_585c20c0da440',
            'label' => 'Contact',
            'name' => 'background_contact',
            'type' => 'image',
            'instructions' => 'Background image for the contact page.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_58653af5fb2ab',
            'label' => '404',
            'name' => 'background_404',
            'type' => 'image',
            'instructions' => 'Background image for the 404 error page.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_58629f3300c78',
            'label' => 'Fallback',
            'name' => 'background_fallback',
            'type' => 'image',
            'instructions' => 'Background image for other pages.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_5874e3734eed5',
            'label' => 'Opening hours',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5874e2b23d83c',
            'label' => 'Open monday-thursday',
            'name' => 'open_mon_thu',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5874e2e23d840',
            'label' => 'Open friday',
            'name' => 'open_fri',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5874e2e33d841',
            'label' => 'Open saturday',
            'name' => 'open_sat',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5874e2e53d842',
            'label' => 'Open sunday',
            'name' => 'open_sun',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_586311a42a5ea',
    'title' => 'Menu',
    'fields' => array (
        array (
            'key' => 'field_5863acb57522b',
            'label' => 'Menu information',
            'name' => 'menu_information',
            'type' => 'textarea',
            'instructions' => 'Welcoming text for menu page',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'wpautop',
        ),
        array (
            'key' => 'field_586311ad62fad',
            'label' => 'Menu Section',
            'name' => 'menu_section',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add Menu',
            'min' => '',
            'max' => '',
            'layouts' => array (
                array (
                    'key' => '586311c071a1b',
                    'name' => 'menu_block',
                    'label' => 'Menu Block',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_58639f2828b63',
                            'label' => 'Menu title',
                            'name' => 'menu_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_58639ebe9c8e8',
                            'label' => 'Add dish',
                            'name' => 'add_dish',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => '',
                            'max' => '',
                            'layout' => 'table',
                            'button_label' => 'Add Dish',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_58639ef9ef356',
                                    'label' => 'Select dish',
                                    'name' => 'dish_select',
                                    'type' => 'post_object',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array (
                                        0 => 'dishes',
                                    ),
                                    'taxonomy' => array (
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'return_format' => 'object',
                                    'ui' => 1,
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_58639f3628b64',
                            'label' => 'Menu description',
                            'name' => 'menu_description',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'wpautop',
                        ),
                        array (
                            'key' => 'field_586f9841f6897',
                            'label' => 'Tasting menu',
                            'name' => 'tasting_menu_select',
                            'type' => 'true_false',
                            'instructions' => 'Is this a tasting menu that should have one single price?',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                        ),
                        array (
                            'key' => 'field_586f98d2f6898',
                            'label' => 'Tasting menu price',
                            'name' => 'tasting_menu_price',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_586f9841f6897',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '$',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page',
                'operator' => '==',
                'value' => '242',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'featured_image',
    ),
    'active' => 1,
    'description' => '',
));

endif;